# Описание датасета

![](https://storage.googleapis.com/kaggle-datasets-images/1617785/2659800/c06a7a3de61a874af446f350118ca9ca/dataset-cover.jpg?t=2021-09-28-18-06-09)
<br>Представлен датасет с данными об игроках режима «Карьера» компьютерной игры FIFA 2022 (датасет выложен на платформе [Kaggle](https://www.kaggle.com/datasets/stefanoleone992/fifa-22-complete-player-dataset)).

**Формат файла** : *csv*

**Ссылка на файл** : https://drive.google.com/file/d/1TO3ZFteyoxQ1GQYrs9Y3hDSdhxXDpx1u/view?usp=share_link

# Обзор датасета. Библиотека Pandas

In [11]:

!pip install -U gdown -q

In [12]:
# скачайте датасет с помощью команды !gdown
!gdown 1TO3ZFteyoxQ1GQYrs9Y3hDSdhxXDpx1u -O dataset.csv

Downloading...
From: https://drive.google.com/uc?id=1TO3ZFteyoxQ1GQYrs9Y3hDSdhxXDpx1u
To: /content/dataset.csv
100% 13.6M/13.6M [00:00<00:00, 61.7MB/s]

In [13]:
# импортируйте библиотеку pandas
import pandas as pd
import numpy as np

In [14]:
# прочитайте датасет и сохраните его в переменную
df = pd.read_csv("dataset.csv")

/tmp/ipykernel_7958/2845491335.py:2: DtypeWarning: Columns (25,108) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("dataset.csv")

In [15]:
# проведите визуальный обзор датасета
df.head()

,sofifa_id,player_url,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,...,lcb,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,"RW, ST, CF",93,93,78000000.0,320000.0,34,...,50+3,50+3,50+3,61+3,19+3,https://cdn.sofifa.net/players/158/023/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,https://cdn.sofifa.net/teams/1369/60.png,https://cdn.sofifa.net/flags/ar.png
1,188545,https://sofifa.com/player/188545/robert-lewand...,R. Lewandowski,Robert Lewandowski,ST,92,92,119500000.0,270000.0,32,...,60+3,60+3,60+3,61+3,19+3,https://cdn.sofifa.net/players/188/545/22_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/1353/60.png,https://cdn.sofifa.net/flags/pl.png
2,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"ST, LW",91,91,45000000.0,270000.0,36,...,53+3,53+3,53+3,60+3,20+3,https://cdn.sofifa.net/players/020/801/22_120.png,https://cdn.sofifa.net/teams/11/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1354/60.png,https://cdn.sofifa.net/flags/pt.png
3,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Júnior,"LW, CAM",91,91,129000000.0,270000.0,29,...,50+3,50+3,50+3,62+3,20+3,https://cdn.sofifa.net/players/190/871/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,NaN,https://cdn.sofifa.net/flags/br.png
4,192985,https://sofifa.com/player/192985/kevin-de-bruy...,K. De Bruyne,Kevin De Bruyne,"CM, CAM",91,91,125500000.0,350000.0,30,...,69+3,69+3,69+3,75+3,21+3,https://cdn.sofifa.net/players/192/985/22_120.png,https://cdn.sofifa.net/teams/10/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1325/60.png,https://cdn.sofifa.net/flags/be.png

In [16]:
# определите количество ячеек в датафрейме (строки X столбцы)
df.size

2116290

In [17]:
# определите количество наблюдений в датафрейме
len(df)

19239

In [18]:
# определите количество признаков в датафрейме
len(df.axes[1])

110

In [19]:
# определите тип данных по признаку 'wage_eur'
df['wage_eur'].dtypes

dtype('float64')

# Исключение признаков, работа с дубликатами

In [20]:
# создайте копию датафрейма, сохранив его в переменную df1
df1 = df.copy()

In [21]:
# список столбцов, которые необходимо исключить
columns = ['club_position',
 'club_jersey_number',
 'club_loaned_from',
 'club_joined',
 'club_contract_valid_until',
 'nationality_id',
 'nationality_name',
 'nation_team_id',
 'nation_position',
 'nation_jersey_number',
 'preferred_foot',
 'weak_foot',
 'skill_moves',
 'international_reputation',
 'work_rate',
 'body_type',
 'real_face',
 'release_clause_eur',
 'player_tags',
 'player_traits',
 'pace',
 'shooting',
 'passing',
 'dribbling',
 'defending',
 'physic',
 'attacking_crossing',
 'attacking_finishing',
 'attacking_heading_accuracy',
 'attacking_short_passing',
 'attacking_volleys',
 'skill_dribbling',
 'skill_curve',
 'skill_fk_accuracy',
 'skill_long_passing',
 'skill_ball_control',
 'movement_acceleration',
 'movement_sprint_speed',
 'movement_agility',
 'movement_reactions',
 'movement_balance',
 'power_shot_power',
 'power_jumping',
 'power_stamina',
 'power_strength',
 'power_long_shots',
 'mentality_aggression',
 'mentality_interceptions',
 'mentality_positioning',
 'mentality_vision',
 'mentality_penalties',
 'mentality_composure',
 'defending_marking_awareness',
 'defending_standing_tackle',
 'defending_sliding_tackle',
 'goalkeeping_diving',
 'goalkeeping_handling',
 'goalkeeping_kicking',
 'goalkeeping_positioning',
 'goalkeeping_reflexes',
 'goalkeeping_speed',
 'ls',
 'st',
 'rs',
 'lw',
 'lf',
 'cf',
 'rf',
 'rw',
 'lam',
 'cam',
 'ram',
 'lm',
 'lcm',
 'cm',
 'rcm',
 'rm',
 'lwb',
 'ldm',
 'cdm',
 'rdm',
 'rwb',
 'lb',
 'lcb',
 'cb',
 'rcb',
 'rb',
 'gk',
 'player_face_url',
 'club_logo_url',
 'club_flag_url',
 'nation_logo_url',
 'nation_flag_url']

In [22]:
# исключите столбцы списка columns из датафрейма, автоматически перезаписав его
df1.drop(columns=columns, inplace=True)

In [23]:
# определите количество признаков в датафрейме
len(df1.axes[1])

17

In [24]:
# определите количество "полных" дубликатов
# (именно повторно встречающихся записей, первые записи не помечаются)
df1.duplicated().sum()

np.int64(0)

In [25]:
# определите количество дубликатов по признакам 'short_name' и 'age' (при условии совпадения значений по обоим признакам)
# (именно повторно встречающихся записей, первые записи не помечаются)
df1.duplicated(subset=['short_name', 'age'], keep=False).sum()

np.int64(186)

In [26]:
# исключите все записи, по которым совпадают значения по признакам 'long_name' и 'club_name'
# (автоматически перезапишите датафрейм)
df1.drop_duplicates(subset=['long_name', 'club_name'], keep=False, inplace=True)

In [27]:
# определите количество записей после исключения дубликатов
len(df1)

19233

# Работа с пропусками

In [28]:
# определите, по каким признакам присутствуют пропущенные значения
df1.isna().sum()

sofifa_id            0
player_url           0
short_name           0
long_name            0
player_positions     0
overall              0
potential            0
value_eur           74
wage_eur            61
age                  0
dob                  0
height_cm            0
weight_kg            0
club_team_id        61
club_name           61
league_name         61
league_level        61
dtype: int64

In [29]:
# определите процент пропусков по признаку 'value_eur'
df1['value_eur'].isnull().mean() * 100

np.float64(0.3847553683772682)

In [30]:
# определите количество заполненных значений по признаку 'league_name'
df1['league_name'].notnull().sum()

np.int64(19172)

In [31]:
# исключите все записи, по которым отсутствуют значения по признаку 'club_name'
# (автоматически перезапишите датафрейм)
df1.dropna(subset=['club_name'], inplace=True)

In [32]:
# определите количество пропущенных значений по признаку 'value_eur'
df1['value_eur'].isna().sum()

np.int64(13)

In [33]:
# найдите среднее значение по признаку 'value_eur'
mean = int(df1['value_eur'].mean())

In [34]:
# заполните средним значением отсутствующие значения по признаку 'value_eur'
# (автоматически перезапишите датафрейм)
df1['value_eur'] = df1['value_eur'].fillna(mean)

In [35]:
# сбросьте индексы после всех преобразований
# (автоматически перезапишите датафрейм)
df1.reset_index(drop=True, inplace=True)

In [36]:
# проверьте диапазон индексов
df1.index

RangeIndex(start=0, stop=19172, step=1)

In [37]:
df1['value_eur'].dtypes

dtype('float64')

# Преобразование данных

In [38]:
# определите формат данных признака 'dob'
df1.dob.dtypes

dtype('O')

In [39]:
# переведите значения признака 'dob' в формат datetime
df1.dob = pd.to_datetime(df1.dob)

In [40]:
# отобразите даты в формате ДД.ММ.ГГГГ
df1.dob = pd.to_datetime(df1.dob, format="%d.%m.%Y")

In [41]:
# определите формат данных признака 'overall'
df1.overall.dtypes

dtype('int64')

In [42]:
# переведите значения признака 'overall' в формат числа с плавающей точкой
pd.to_datetime(df1.overall, unit='s', origin='unix')

0       1970-01-01 00:01:33
1       1970-01-01 00:01:32
2       1970-01-01 00:01:31
3       1970-01-01 00:01:31
4       1970-01-01 00:01:31
                ...
19167   1970-01-01 00:00:47
19168   1970-01-01 00:00:47
19169   1970-01-01 00:00:47
19170   1970-01-01 00:00:47
19171   1970-01-01 00:00:47
Name: overall, Length: 19172, dtype: datetime64[ns]

In [43]:
# определите формат данных признака 'value_eur'
df1.value_eur.dtypes

dtype('float64')

In [44]:
# переведите значения признака 'value_eur' в формат целого числа
df1.value_eur = df1.value_eur.astype('int64')

# Расчёт доп. признаков

In [45]:
# рассчитайте актуальный возраст на текущий год (без учета дня и месяца рождения) и сохраните данные в столбец 'age_new'
current_day = pd.Timestamp.today()
current_day
current_year = current_day.year
current_year
df1['age_new'] = current_year - df1.dob.apply(lambda x: x.year)
df1.age_new

0        39
1        38
2        41
3        34
4        35
         ..
19167    27
19168    24
19169    26
19170    24
19171    24
Name: age_new, Length: 19172, dtype: int64

In [46]:
# определите разницу в возрасте (количество лет) между футболистами под индексом 0 и 10017
age = df1.loc[0, 'age_new'] - df1.loc[10017, 'age_new']
age

np.int64(5)

In [47]:
# определите индекс массы тела футболистов, округлив результат до двух знаков после запятой
# запишите результаты в столбец 'imt'
# ИМТ = вес (в килограммах) : (рост (м))**2
# вес - 'weight_kg', рост - 'height_cm'
df1['imt'] = df1['weight_kg'] / ((df1['height_cm'] / 100) ** 2)
df1['imt'] = df1['imt'].apply(lambda x: float(f"{x:.2f}"))

In [48]:
# определите среднее значение ИМТ с помощью метода mean(), округлив результат до двух знаков после запятой
float(f"{df1['imt'].mean():.2f}")

22.77

In [49]:
# закодируйте значения по признаку 'player_positions' по условию:
# если указано одно значение, то присвоить 0, в противном случае - 1
# результаты сохраните в столбец 'player_positions_code'
# подсказка: количество значений можно определить как длину списка, определенного с помощью метода split()
df1['player_positions_code'] = df1['player_positions'].apply(
    lambda x: 0 if len(x.split(', ')) == 1 else 1
)

In [50]:
# определите наиболее часто встречаемое значение по признаку 'player_positions_code'
# подсказка: используйте метод mode()
ones = df1['player_positions_code'].sum()
zeros = len(df1) - ones
1 if ones > zeros else 0

1

In [51]:
# закодируйте значения по признаку 'player_positions_code' с помощью словаря:
# 0: one, 1: several
# результаты сохраните в столбец 'player_positions_category'
player_positions_dict = {0: 'one', 1: 'several'}
df1['player_positions_category'] = df1['player_positions_code'].apply(lambda x: player_positions_dict[x])

In [52]:
# определите количество значений several по признаку 'player_positions_category'
# подсказка: для вывода булевых значений используйте оператор сравнения
# подсказка: для расчета количества используйте метод sum()
(df1['player_positions_category'] == 'several').sum()

np.int64(9776)

# Форматирование текстовых данных

In [53]:
# определите количество уникальных значений по признаку 'league_name'
print(len(df1['league_name'].unique()))

55

In [54]:
# приведите строковые значения признака 'league_name' в нижний регистр
df1['league_name'] = df1['league_name'].str.lower()

In [55]:
# определите, сколько раз встречается подстрока 'russia' в строковых данных признака 'league_name'
df1['league_name'].str.contains('russia').sum()

np.int64(82)

In [56]:
# заполните все пустые значения по признаку 'league_name' значением 'не указано'
df1['league_name'].fillna('не указано', inplace=True)

In [57]:
# замените значения 'не указано' по признаку 'league_name' на значение 'undefined'
df1['league_name'] = df1['league_name'].apply(lambda x: 'undefined' if x == 'не указано' else x)

In [58]:
# определите, сколько раз встречается подстрока 'undefined' в строковых данных признака 'league_name'
df1['league_name'].str.contains('undefined').sum()

np.int64(0)

In [59]:
# разделите строки по признаку 'player_positions' на список подстрок
df1['player_positions'] = df1['player_positions'].apply(lambda x: x.split(', '))

In [60]:
# трансформируйте датафрейм по признаку 'player_positions' и сохраните его в переменную df2
df2 = df1.explode('player_positions', ignore_index=True)

In [61]:
# определите количество наблюдений в датафрейме df2
len(df2)

31836

In [62]:
# сохраните датафрейм df1 в формат xlsx без учета индексного столбца
df1.to_excel('players_22_clean.xlsx', index=False)

In [63]:
# сохраните датафрейм df2 в формат csv
df2.to_csv('players_22_clean.csv')